version: "3"

services:
  traefik:
    # The official v2 Traefik docker image
    image: traefik:v2.7
    container_name: traefik
    restart: always
    # env_file: env
    command:
      - --global.sendAnonymousUsage=false
      # Enable Dashboard
      - --api.insecure=true
      - --api.dashboard=true
      - --api.debug=true
      # We are using Docker
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      # Listen on port 8080 (traefik Dashboard)
      # - --entrypoints.traefik_http.address=:8080
      # Listen on port 80 (http)
      - --entrypoints.web.address=:80
      # Listen on port 443 (https)
      - --entrypoints.websecure.address=:443
      # Automaticly redirect from http to https
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      # Listen on port 3306 (MySQL)
      # - --entrypoints.mysql.address=:3306
      # Enable LetsEncrypt
      #- --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      #- --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      #- --certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}
      #- --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      # Enable Access Log
      - --accesslog.filepath=/var/log/www/access.log
    ports:
      # The HTTP port
      - "80:80"
      # The HTTPS port
      - "443:443"
      # The Web UI (enabled by --api.insecure=false)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # LetsEncrypt Configuration Storage
      - ./letsencrypt:/letsencrypt
      # Enable Access Log
      - ./logs/:/var/log/www/
    #labels:
    #- traefik.enable=true
    #- traefik.http.routers.traefik_http.entrypoints=traefik_http
    #- traefik.http.routers.traefik_http.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)
    #- traefik.http.routers.traefik_http.rule=Host(`${HOSTNAME}`)
    #- traefik.http.routers.traefik_http.tls=true
    #- traefik.http.routers.traefik_http.tls.certResolver=letsencrypt
    #- traefik.http.routers.traefik_http.service=api@internal
    # Username: nadmin
    # Password: EnterPasswordHere
    # Encrypt Password via 'echo $(htpasswd -nB nadmin) | sed -e s/\\$/\\$\\$/g'
    #- traefik.http.routers.traefik_https.middlewares=traefik-auth
    #- traefik.http.middlewares.traefik-auth.basicauth.users=nadmin:EnterEncryptedPasswordHere
    networks:
      - traefik_ext
      - traefik_int

networks:
  traefik_ext:
    external: true
  traefik_int:
    internal: true
