services:
  traefik:
    command:
      # By default, the level is set to ERROR. Alternative logging levels are 
      # DEBUG, PANIC, FATAL, ERROR, WARN, and INFO.
      - --log.level=ERROR
      - --global.sendAnonymousUsage=false
      # Enable Dashboard
      - --api.insecure=false
      - --api.dashboard=true
      - --api.debug=true
      # We are using Docker
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      # (Optional) Set default hostname if not given explicitly
      - --providers.docker.defaultRule=Host("${CUSTOM_HOSTNAME}")
      # Listen on port 80 (http)
      - --entrypoints.web.address=:80
      # Listen on port 443 (https)
      - --entrypoints.websecure.address=:443
      # Listen on port 8080 (traefik Dashboard)
      - --entrypoints.traefik_https.address=:8080
      # Automaticly redirect from http to https
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https

      ################ START SSL configuration ################
      # ---------> Cloudflare <---------
      # DNS challenge via Cloudflare
      - --certificatesresolvers.cloudflare.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.cloudflare.acme.storage=/ssl/acme.json
      - --certificatesresolvers.cloudflare.acme.dnsChallenge.provider=cloudflare
      - --certificatesresolvers.cloudflare.acme.dnsChallenge.delayBeforeCheck=60
      - --certificatesresolvers.cloudflare.acme.dnsChallenge.resolvers=1.1.1.1:53
      # (Optional) Use testing server before receiving the productive ssl certificate
      - --certificatesresolvers.cloudflare.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
      # --------------------------------
      ################  END SSL configuration  ################

      - --entrypoints.websecure.http.tls.domains[0].main=${CUSTOM_HOSTNAME}
      # (Optional) Use only, if you are able to receive a wildcard ssl certificate
      - --entrypoints.websecure.http.tls.domains[0].main=*.${CUSTOM_HOSTNAME}
      # Enable Access Log
      - --accesslog.filepath=/var/log/www/access.log
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # LetsEncrypt Configuration Storage
      - ./ssl:/ssl
      # Enable Access Log
      - ./logs/:/var/log/www/
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_ext

      - traefik.http.routers.traefik_https.entrypoints=traefik_https
      - traefik.http.routers.traefik_https.rule=Host(`${CUSTOM_HOSTNAME}`) && PathPrefix(`/api`) || PathPrefix(`/dashboard`)
      - traefik.http.routers.traefik_https.tls=true
      - traefik.http.routers.traefik_https.tls.certResolver=cloudflare
      - traefik.http.routers.traefik_https.service=api@internal
