version: "3"

services:
  whoami:
    image: traefik/whoami
    container_name: whoami
    restart: unless-stopped
    environment:
      - CUSTOM_HOSTNAME: "domain.tld"
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_ext
      #- traefik.http.routers.whoami.entrypoints=web
      - traefik.http.routers.whoami.entrypoints=websecure
      - traefik.http.routers.whoami.rule=Host(`whoami.${CUSTOM_HOSTNAME}`)
      - traefik.http.routers.whoami.tls=true
    networks:
      - traefik_ext

networks:
  traefik_ext:
    external: true
