version: "3"

services:
  whoami:
    image: traefik/whoami
    container_name: whoami
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_ext
      #- traefik.http.routers.whoami.entrypoints=web
      - traefik.http.routers.whoami.entrypoints=websecure
      
      # -------------> CHANGE DOMAIN NAME HERE <-------------
      - traefik.http.routers.whoami.rule=Host(`whoami.domain.tld`)
      # <--------------------------------------------------->
      - traefik.http.routers.whoami.tls=true
    networks:
      - traefik_ext

networks:
  traefik_ext:
    external: true
